config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :ingredients, only: [:index, :new, :create]
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo

  validates :name, uniqueness: true
  validates :name, presence: true
  validates :photo, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save!
      redirect_to new_cocktail_dose_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    @dose.save!

    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy

    redirect_to cocktail_path(@dose.cocktail)
    end

  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(set_params)
    if @ingredient.save
      redirect_to ingredients_path
    else
      render :new
    end
  end

  private

  def set_params
    params.require(:ingredient).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.6)), url(https://images.unsplash.com/photo-1519214605650-76a613ee3245?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1049&q=80);">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-12">
        <div class="d-flex flex-column justify-content-center align-items-center">
          <i class="fas fa-glass-martini-alt"></i>
          <h1 class="mb-3">Au 13,</h1>
          <p>Venez, <span id="banner-typed-text"></span></p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="d-flex justify-content-center">
  <div class="title title-small d-flex justify-content-between align-items-center">
    <h1 class="m-3">Nos cocktails</h1>
    <%= link_to "Ajouter un cocktail", new_cocktail_path, class:"btn btn-success mr-3" %>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="d-flex justify-content-center flex-wrap present">
        <% @cocktails.each do |cocktail| %>
          <%= link_to cocktail_path(cocktail) do %>
            <div class="card">
                <%= cl_image_tag cocktail.photo.key, :height=>256, :width=> 298, crop: :fill %>
              <div class="card-info">
                <h3 class="pl-2"><%= cocktail.name %></h3>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <%= link_to "Les ingredients", ingredients_path %> du 13
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "A la maison", cocktails_path, class: "btn btn-success" %>
      </li>
    </ul>
  </div>
</div>
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-6">
      <%= simple_form_for(@cocktail) do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class:"btn btn-warning" %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "A la maison", cocktails_path, class: "btn btn-success" %>
      </li>
    </ul>
  </div>
  <div>
    <%= link_to "Ajouter des ingredients", new_cocktail_dose_path(@cocktail), class:"btn btn-success" %>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-12 col-md-6">
      <div class="card-show">
        <%= cl_image_tag @cocktail.photo.key, :width=>400, :height=>500, crop: :fill %>
        <h3>Ingrédients</h3>
        <ol>
          <% @cocktail.doses.each do |dose| %>
            <li style="color: $gray"><%= dose.ingredient.name %>: <%= dose.description %>
              <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </li>
          <% end %>
        </ol>
      </div>
    </div>
  </div>
</div>
<div class="footer fixed-bottom">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <%= link_to "Tous nos ingredients", ingredients_path %> au 13
  </div>
</div>

app/views/doses/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= simple_form_for([@cocktail, @dose]) do |f| %>
        <%= f.input :description %>
        <%= f.association :ingredient %>
        <%= f.button :submit, class:"btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/ingredients/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "A la maison", cocktails_path, class: "btn btn-success" %>
      </li>
    </ul>
  </div>
  <div>
    <%= link_to "Ajouter un ingredient", new_ingredient_path , class:"btn btn-success" %>
  </div>
</div>
<div class="container mt-5">
  <div class="row">
    <div class="col-6">
      <h1 style="color: white">Liste de nos ingredients</h1>
      <ol>
        <% @ingredients.each do |ingredient| %>
          <li style="color: white"><%= ingredient.name %></li>
        <% end %>
      </ol>
    </div>
  </div>
</div>

app/views/ingredients/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= simple_form_for(@ingredient) do |f| %>
        <%= f.input :name %>
        <%= f.button :submit, class:"btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>